name: calculo_maluco
description: Crazy Calculus is a kids game to learn math operations.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  emoji_alert: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.4
  audioplayers: ^0.20.1

flutter_icons:
  android: "launcher_icon"  
  ios: true
  image_path_android: "assets/icon.png"  
  image_path_ios: "assets/icon.png"  

flutter_native_splash:
  color: "#4e54c8"
  image: assets/icon.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter: 
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/music.mp3